### PR TITLE
:lock: Fix vulnerabilities in prod dependencies

### PR DESCRIPTION
**Pull request by quilicicf**
Hi, 

This commit should remove CVEs on production dependencies.

The tests were failing on master, I did not fix them, I'm afraid I don't have much time right now :(

### CODE REVIEW

**Comment by bendorshai** [comment]
> Hi,
> 
> This commit should remove CVEs on production dependencies.
> 
> The tests were failing on master, I did not fix them, I'm afraid I don't have much time right now :(

don't be afraid, have you run the testers? they should give you sense of calmness :)

**Comment by quilicicf** [comment]
I've run `npm test` but got errors: 

```
npm test

> its-a-date@1.2.13 test ~/forge/its-a-date
> tape test.js | tap-min

~/forge/its-a-date/testers/persian.js:10
    t.equal(parse("ژانوِیه").getMonth(), 0, 'Pr jan');
                            ^

TypeError: Cannot read property 'getMonth' of undefined
    at Test.t (~/forge/its-a-date/testers/persian.js:10:29)
    at Test.bound [as _cb] (~/forge/its-a-date/node_modules/tape/lib/test.js:63:32)
    at Test.run (~/forge/its-a-date/node_modules/tape/lib/test.js:82:10)
    at Test.bound [as run] (~/forge/its-a-date/node_modules/tape/lib/test.js:63:32)
    at Immediate.next (~/forge/its-a-date/node_modules/tape/lib/results.js:70:15)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

178 tests complete (161ms)
npm ERR! Test failed.  See above for more details.
```

Since I got them on `master` too, I can't tell whether my changes add regressions or not :(

**Comment by quilicicf** [comment]
@bendorshai Any news on this?

**Comment by bendorshai** [comment]
Im sorry, I am not working on this project anymore, feel free to fork and improve

**Pull request closed without merging**
